spring:
  application:
    name: server
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
    open-in-view: false
  profiles:
    active: prod

springdoc:
  packages-to-scan: kr.vipwave.server
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
